#!/bin/bash

packages_dir=node_modules
node_root=/opt/node

[ "$SERVICE_NODE_VERSION" ] && 
[ "$SERVICE_NODE_VERSION" != "$(node --version)" ] &&
(
    rm -rf $node_root/*
    cd $node_root
    curl -L https://github.com/joyent/node/tarball/$SERVICE_NODE_VERSION | tar -zxf-
    cd joyent-node-*
    ./configure --prefix=$node_root
    make
    make install
)

cd ${SERVICE_APPROOT:=.}

# Some user have their packages in their repository let's remove them,
# there is good chances that we are on a different architecture anyway.
[ -e "$packages_dir" ] && rm -rf "$packages_dir"

# Copy code to $HOME.
rsync -aH ./ $HOME/

# Install the specified dependencies.
# This will re-use already installed dependencies.
# To force the use of the latest version of a package:
# - specify a version specification in package.json;
# - or push with the "--clean" flag to discard the incremental build.
cd $HOME
[ -f package.json ] && npm install && npm install -g


rm -rf ./public
mkdir -p ./public/templates
mkdir -p ./public/js
mkdir -p ./public/js/ext
mkdir -p ./public/css
mkdir -p ./public/img

# Templates
jaded -a "jade" -i ./client/templates -o ./public/templates

# CoffeeScript
coffee -o ./public/js/ -c ./client/js/

# TODO - process that minifies all js
# uglifyjs -nc --unsafe -mt -o ./public/js/main.min.js ./public/js/main.js

# Non-built files
cp ./client/*.html ./public
cp -R ./client/js/ext/* ./public/js/ext
cp -R ./client/css/* ./public/css
cp -R ./client/img/* ./public/img

# Wire public img folder to private location
rm -rf ./store
mkdir ./store
touch ./store/index.html

echo "Build completed!"